
==================[09.03.2020 19:38:22]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:38:26]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 19:39:30]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
=========================================================

==================[09.03.2020 19:39:30]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
=========================================================

==================[09.03.2020 19:39:30]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
=========================================================

==================[09.03.2020 19:39:31]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySqlDataReader MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
=========================================================

==================[09.03.2020 19:39:31]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySqlDataReader MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at int MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at void server_side.Data.House.CreateHouse(Vector3 HousePosition, float rotation, int HousePrice, int HouseClass) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 151
   at void server_side.Data.House.CMD_hcr(Client client, int HousePrice, int HouseClass) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 174
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[09.03.2020 19:39:42]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Linq.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:39:42]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Linq.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:39:42]==================
System.InvalidOperationException: Sequence contains no elements
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
=========================================================

==================[09.03.2020 19:39:42]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no elements
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at void server_side.Data.House.OnPlayerEnterColshape(ColShape shape, Client client) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 165
   at void Main.events.Events.Event_PlayerEnterColshape(ColShape colshape, Client client) in D:\Desktop\nonamerp\bridge\resources\server_side\Events\Events.cs:line 118
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[09.03.2020 19:44:31]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:44:32]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 19:44:48]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
=========================================================

==================[09.03.2020 19:44:48]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
=========================================================

==================[09.03.2020 19:44:48]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
=========================================================

==================[09.03.2020 19:44:48]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySqlDataReader MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
=========================================================

==================[09.03.2020 19:44:48]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySqlDataReader MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at int MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at void server_side.Data.House.CreateHouse(Vector3 HousePosition, float rotation, int HousePrice, int HouseClass) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 151
   at void server_side.Data.House.CMD_hcr(Client client, int HousePrice, int HouseClass) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 174
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[09.03.2020 19:52:39]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:52:40]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 19:52:47]==================
System.InvalidCastException: Unable to cast object of type 'System.Decimal' to type 'System.Double'.
   at void server_side.Events.Auth.Event_GetAccountFromBD(Client client, object[] args)+() => { } in D:\Desktop\nonamerp\bridge\resources\server_side\Events\Auth.cs:line 76
=========================================================

==================[09.03.2020 19:54:54]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
=========================================================

==================[09.03.2020 19:54:54]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
=========================================================

==================[09.03.2020 19:54:54]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
=========================================================

==================[09.03.2020 19:54:54]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySqlDataReader MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
=========================================================

==================[09.03.2020 19:54:54]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: Data truncated for column 'h_enterposX' at row 1
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at int MySql.Data.MySqlClient.NativeDriver.GetResult(ref int affectedRow, ref long insertedId)
   at ResultSet MySql.Data.MySqlClient.Driver.NextResult(int statementId, bool force)
   at bool MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySqlDataReader MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at int MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at void server_side.Data.House.CreateHouse(Vector3 HousePosition, float rotation, int HousePrice, int HouseClass) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 151
   at void server_side.Data.House.CMD_hcr(Client client, int HousePrice, int HouseClass) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 174
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[09.03.2020 19:55:51]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:55:52]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 19:59:03]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 19:59:04]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 20:03:15]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:03:16]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 20:14:00]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:14:00]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 20:15:49]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Linq.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:15:49]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Linq.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:15:49]==================
System.InvalidOperationException: Sequence contains no elements
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
=========================================================

==================[09.03.2020 20:15:49]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.InvalidOperationException: Sequence contains no elements
   at TSource System.Linq.Enumerable.First<TSource>(IEnumerable<TSource> source)
   at void server_side.Data.House.OnPlayerEnterColshape(ColShape shape, Client client) in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 175
   at void Main.events.Events.Event_PlayerEnterColshape(ColShape colshape, Client client) in D:\Desktop\nonamerp\bridge\resources\server_side\Events\Events.cs:line 118
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[09.03.2020 20:16:07]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:16:08]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 20:22:15]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[09.03.2020 20:22:15]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:22:15]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:22:15]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[09.03.2020 20:22:15]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[09.03.2020 20:25:28]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:25:29]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 20:33:13]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:33:14]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 20:50:34]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 20:50:35]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 21:26:44]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 21:26:45]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 21:36:34]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[09.03.2020 21:36:35]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[09.03.2020 21:49:44]==================
System.FormatException: Input string was not in a correct format.
   at void Number.StringToNumber(ReadOnlySpan<char> str, NumberStyles options, ref NumberBuffer number, NumberFormatInfo info, bool parseDecimal)
=========================================================

==================[11.03.2020 14:56:19]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 14:56:22]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 14:56:22]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 14:56:22]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 14:56:22]==================
System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

=========================================================

==================[11.03.2020 14:56:22]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 14:56:22]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 14:56:22]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[11.03.2020 14:56:22]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[11.03.2020 14:56:22]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
=========================================================

==================[11.03.2020 14:56:22]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
=========================================================

==================[11.03.2020 14:56:23]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
   at void server_side.Data.House.InitHouses() in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 43
   at void Main.events.Events.Event_OnResourceStart() in D:\Desktop\nonamerp\bridge\resources\server_side\Events\Events.cs:line 33
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[11.03.2020 15:01:20]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:01:22]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[11.03.2020 15:02:00]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:02:00]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:02:00]==================
System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Http.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:02:01]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Http.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:02:01]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
=========================================================

==================[11.03.2020 15:02:01]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:01]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:02]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:02]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:02]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
=========================================================

==================[11.03.2020 15:02:03]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:03]==================
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
   at async Task<WebResponse> System.Net.HttpWebRequest.SendRequest()
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:03]==================
System.Net.WebException: An error occurred while sending the request. Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
   at async Task<WebResponse> System.Net.HttpWebRequest.SendRequest()
   at WebResponse System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at WebResponse System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
=========================================================

==================[11.03.2020 15:02:03]==================
System.Net.WebException: An error occurred while sending the request. Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.IO.IOException: Unable to read data from the transport connection: Сделана попытка выполнить операцию на сокете при отключенной сети. ---> System.Net.Sockets.SocketException: Сделана попытка выполнить операцию на сокете при отключенной сети
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.ThrowException(SocketError error)
   at int System.Net.Sockets.Socket+AwaitableSocketAsyncEventArgs.GetResult(short token)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.FillBufferAsync<TReadAdapter>(TReadAdapter adapter, int minSize)+InternalFillBufferAsync(?)
   at async ValueTask<int> System.Net.Security.SslStreamInternal.ReadAsyncInternal<TReadAdapter>(TReadAdapter adapter, Memory<byte> buffer)
   at async Task System.Net.Http.HttpConnection.FillAsync()
   at async ValueTask<ArraySegment<byte>> System.Net.Http.HttpConnection.ReadNextResponseHeaderLineAsync(bool foldedHeadersAllowed)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   --- End of inner exception stack trace ---
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnection.SendAsyncCore(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithNtConnectionAuthAsync(HttpConnection connection, HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpConnectionPool.SendWithRetryAsync(HttpRequestMessage request, bool doRequestAuth, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at async Task<HttpResponseMessage> System.Net.Http.HttpClient.FinishSendAsyncUnbuffered(Task<HttpResponseMessage> sendTask, HttpRequestMessage request, CancellationTokenSource cts, bool disposeCts)
   at async Task<WebResponse> System.Net.HttpWebRequest.SendRequest()
   at WebResponse System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   --- End of inner exception stack trace ---
   at WebResponse System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:03]==================
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at async void server_side.Utilities.UtilityFuncs.SetCurrentWeatherInLA() in D:\Desktop\nonamerp\bridge\resources\server_side\Utilities\UtilityFuncs.cs:line 24
=========================================================

==================[11.03.2020 15:02:03]==================
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at async void server_side.Utilities.UtilityFuncs.SetCurrentWeatherInLA() in D:\Desktop\nonamerp\bridge\resources\server_side\Utilities\UtilityFuncs.cs:line 24
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:02:03]==================
System.IndexOutOfRangeException: Index was outside the bounds of the array.
   at async void server_side.Utilities.UtilityFuncs.SetCurrentWeatherInLA() in D:\Desktop\nonamerp\bridge\resources\server_side\Utilities\UtilityFuncs.cs:line 24
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[11.03.2020 15:06:35]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:06:36]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[11.03.2020 15:14:05]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:14:07]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:14:08]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:14:09]==================
System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:14:09]==================
System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   at int MySql.Data.MySqlClient.TimedStream.Read(byte[] buffer, int offset, int count)
=========================================================

==================[11.03.2020 15:14:09]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:14:09]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[11.03.2020 15:14:09]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   at int MySql.Data.MySqlClient.TimedStream.Read(byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
=========================================================

==================[11.03.2020 15:14:09]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:14:09]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:14:09]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[11.03.2020 15:14:09]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   at int MySql.Data.MySqlClient.TimedStream.Read(byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at void MySql.Data.MySqlClient.NativeDriver.ReadOk(bool read)
=========================================================

==================[11.03.2020 15:33:43]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:33:44]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:33:44]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[11.03.2020 15:38:52]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:38:52]==================
System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:38:52]==================
System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   at int MySql.Data.MySqlClient.TimedStream.Read(byte[] buffer, int offset, int count)
=========================================================

==================[11.03.2020 15:38:52]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   at int MySql.Data.MySqlClient.TimedStream.Read(byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
=========================================================

==================[11.03.2020 15:38:52]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:38:52]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[11.03.2020 15:38:52]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[11.03.2020 15:38:52]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Reading from the stream has failed. ---> System.IO.IOException: Unable to read data from the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at int System.Net.Sockets.NetworkStream.Read(byte[] buffer, int offset, int size)
   at int MySql.Data.MySqlClient.TimedStream.Read(byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, byte[] buffer, int offset, int count)
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at void MySql.Data.MySqlClient.MySqlStream.LoadPacket()
   at MySqlPacket MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at void MySql.Data.MySqlClient.NativeDriver.ReadOk(bool read)
=========================================================

==================[21.03.2020 6:47:22]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[21.03.2020 6:47:24]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 0:00:29]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 0:00:34]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 0:19:47]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 0:19:49]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 0:22:06]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 0:22:08]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 0:23:14]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 0:23:16]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 0:24:44]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 0:24:45]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 5:13:47]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 5:13:49]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 5:19:55]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 5:19:55]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 5:19:55]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 5:19:55]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 5:19:55]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[01.04.2020 8:55:09]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 8:55:10]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:02:36]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:02:38]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:08:44]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 9:08:44]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:08:44]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:08:44]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 9:08:44]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[01.04.2020 9:08:59]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:09:01]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:09:54]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:09:55]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:10:57]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:10:58]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:14:38]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:14:40]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:15:41]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:15:43]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:17:19]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:17:21]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:19:51]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:19:54]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:21:06]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:21:08]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:21:43]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:21:45]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:28:49]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:28:50]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:34:59]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:35:00]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:35:11]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:35:12]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:36:39]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:36:40]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:37:22]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:37:23]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:39:24]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:39:26]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:47:38]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:47:41]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:49:32]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:49:34]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:50:58]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:51:00]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:52:50]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:52:52]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:55:05]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:55:07]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:56:30]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:56:31]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 9:57:50]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 9:57:53]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:05:23]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:05:26]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:06:07]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:06:09]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:07:40]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:07:41]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:09:06]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:09:07]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:09:54]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:09:56]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:16:02]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 10:16:02]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:16:02]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:16:03]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 10:16:03]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[01.04.2020 10:16:34]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:16:37]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:18:00]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:18:01]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:19:41]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:19:44]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:21:53]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:21:55]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:28:01]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:28:03]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:35:11]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:35:12]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 10:45:59]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 10:46:00]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 11:09:33]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 11:09:33]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 11:36:18]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 11:36:20]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 11:42:27]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 11:42:27]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 11:42:27]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 11:42:27]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[01.04.2020 11:42:27]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[01.04.2020 12:03:21]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 12:03:22]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[01.04.2020 12:07:09]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[01.04.2020 12:07:10]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[02.04.2020 14:11:10]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 14:11:12]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[02.04.2020 14:11:13]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[02.04.2020 14:11:13]==================
System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
=========================================================

==================[02.04.2020 14:11:13]==================
System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

=========================================================

==================[02.04.2020 14:11:13]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 14:11:13]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 14:11:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
=========================================================

==================[02.04.2020 14:11:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
=========================================================

==================[02.04.2020 14:11:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
=========================================================

==================[02.04.2020 14:11:13]==================
MySql.Data.MySqlClient.MySqlException (0x80004005): Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
---> (Inner Exception #0) System.Net.Internals.SocketExceptionFactory+ExtendedSocketException (10061): Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)<---

   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
=========================================================

==================[02.04.2020 14:11:13]==================
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> MySql.Data.MySqlClient.MySqlException: Unable to connect to any of the specified MySQL hosts. ---> System.AggregateException: One or more errors occurred. (Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306) ---> System.Net.Internals.SocketExceptionFactory+ExtendedSocketException: Подключение не установлено, т.к. конечный компьютер отверг запрос на подключение 127.0.0.1:3306
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at bool System.Net.Sockets.Socket.DoMultipleAddressConnectCallback(object result, MultipleAddressConnectAsyncResult context)
   at void System.Net.Sockets.Socket.MultipleAddressConnectCallback(IAsyncResult result)
   at void System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   at void System.Net.Sockets.TcpClient.EndConnect(IAsyncResult asyncResult)
   at void System.Threading.Tasks.TaskFactory<TResult>.FromAsyncCoreLogic(IAsyncResult iar, Func<IAsyncResult, TResult> endFunction, Action<IAsyncResult> endAction, Task<TResult> promise, bool requiresSynchronization)
   --- End of inner exception stack trace ---
   at bool System.Threading.Tasks.Task.Wait(int millisecondsTimeout, CancellationToken cancellationToken)
   at Stream MySql.Data.Common.StreamCreator.GetTcpStream(MySqlConnectionStringBuilder settings)
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   --- End of inner exception stack trace ---
   at void MySql.Data.MySqlClient.NativeDriver.Open()
   at void MySql.Data.MySqlClient.Driver.Open()
   at Driver MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at Driver MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at Driver MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at Driver MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at void MySql.Data.MySqlClient.MySqlConnection.Open()
   at void server_side.Data.House.InitHouses() in D:\Desktop\nonamerp\bridge\resources\server_side\Data\House.cs:line 43
   at void Main.events.Events.Event_OnResourceStart() in D:\Desktop\nonamerp\bridge\resources\server_side\Events\Events.cs:line 33
   --- End of inner exception stack trace ---
   at object RuntimeMethodHandle.InvokeMethod(object target, object[] arguments, Signature sig, bool constructor, bool wrapExceptions)
   at object System.Reflection.RuntimeMethodInfo.Invoke(object obj, BindingFlags invokeAttr, Binder binder, object[] parameters, CultureInfo culture)
=========================================================

==================[02.04.2020 14:32:37]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 14:32:38]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[02.04.2020 14:41:45]==================
System.Net.Sockets.SocketException (10053): Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[02.04.2020 14:41:45]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 14:41:45]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'System.Net.Sockets.resources'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 14:41:45]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
=========================================================

==================[02.04.2020 14:41:46]==================
System.IO.IOException: Unable to write data to the transport connection: Программа на вашем хост-компьютере разорвала установленное подключение. ---> System.Net.Sockets.SocketException: Программа на вашем хост-компьютере разорвала установленное подключение
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   --- End of inner exception stack trace ---
   at void System.Net.Sockets.NetworkStream.Write(byte[] buffer, int offset, int size)
   at void MySql.Data.MySqlClient.TimedStream.Write(byte[] buffer, int offset, int count)
=========================================================

==================[02.04.2020 15:33:09]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 15:33:10]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[02.04.2020 15:34:50]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 15:34:51]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[02.04.2020 15:38:00]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 15:38:01]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================

==================[02.04.2020 15:50:38]==================
System.IO.FileNotFoundException: Could not load the specified file.
File name: 'MySql.Data'
   at Assembly System.Runtime.Loader.AssemblyLoadContext.ResolveUsingEvent(AssemblyName assemblyName)
=========================================================

==================[02.04.2020 15:50:39]==================
System.ArgumentException: 'iso-2022-cn' is not a supported encoding name. For information on defining a custom encoding, see the documentation for the Encoding.RegisterProvider method.
Parameter name: name
   at int System.Text.EncodingTable.internalGetCodePageFromName(string name)
=========================================================
